app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/',                 ['as' => 'home',    'uses' => 'PagesController@home']);
Route::get('about',             ['as' => 'about',   'uses' => 'PagesController@about']);
Route::get('about/contact',     ['as' => 'contact', 'uses' => 'PagesController@contact']);

Route::resource('missions', 'MissionsController');
Route::resource('missions.attempts', 'AttemptsController', ['only' => ['store', 'update', 'edit', 'destroy']]);

Route::get('profile',           ['as' => 'profile.edit',    'uses' => 'ProfileController@edit']);
Route::put('profile',           ['as' => 'profile.update',  'uses' => 'ProfileController@update']);

// Authentication routes...
Route::get('auth/login',        ['as' => 'auth.login',      'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login',       ['as' => 'auth.accept',     'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout',       ['as' => 'auth.logout',     'uses' => 'Auth\AuthController@getLogout']);

// Registration routes...
Route::get('auth/register',     ['as' => 'auth.register',   'uses' => 'Auth\AuthController@getRegister']);
Route::post('auth/register',    ['as' => 'auth.store',     'uses' => 'Auth\AuthController@postRegister']);

Route::get('auth/email-available', ['as' => 'auth.email-available', 'uses' => 'Auth\AuthController@getEmailAvailable']);

// Password reset link request routes...
Route::get('password/email',    ['as' => 'password.email',  'uses' => 'Auth\PasswordController@getEmail']);
Route::post('password/email',   ['as' => 'password.send',   'uses' => 'Auth\PasswordController@postEmail']);

// Password reset routes...
Route::get('password/reset/{token}',    ['as' => 'password.reset',  'uses' => 'Auth\PasswordController@getReset']);
Route::post('password/reset',           ['as' => 'password.accept', 'uses' => 'Auth\PasswordController@postReset']);

/*

/

/login
/logout
/register
/forgot-password

/missions -- list of all missions
/missions/create
/missions/{id}
    -- mission and
    list of all attempts,
    form for new attempts
    as admin/owner of mission, ability to mark attempts as passed etc.

/missions/{id}/edit

/user/{username} -- user and all missions attempted

/leaderboard

*/

app/Mission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Codesleeve\Stapler\ORM\StaplerableInterface;
use Codesleeve\Stapler\ORM\EloquentTrait;

class Mission extends Model implements StaplerableInterface
{

    use EloquentTrait;
    
    protected $fillable = ['title', 'description', 'photo'];

    function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function attempts()
    {
        return $this->hasMany(Attempt::class);
    }

    public function __construct(array $attributes = array())
    {
        $this->hasAttachedFile('photo', [
            'styles' => [
                'hero' => [
                    'dimensions' => '1170x400#',
                    'convert_options' => ['quality' => 60]
                ],
                'medium' => '300x300',
                'thumb' => '100x100'
            ]
        ]);

        parent::__construct($attributes);
    }
}

app/Http/Controllers/MissionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\CreateMissionRequest;
use App\Http\Requests\UpdateMissionRequest;
use App\Http\Controllers\Controller;
use App\Mission;

class MissionsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $missions = Mission::with('user')->get();

        return view('missions.index', compact('missions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $mission = new Mission;

        return view('missions.create', compact('mission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(CreateMissionRequest $request)
    {
        $mission = new Mission($request->all());
        $mission->user()->associate($request->user());
        $mission->save();

        return redirect()->route('missions.show', $mission->id)
            ->with('status.success', 'Success! Your mission is now live!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $mission = Mission::findOrFail($id);
        $attempts = $mission->attempts()->with('user')->get();

        $attemptTally = count($attempts);
        $successTally = count($mission->attempts()->where('status', 'success')->get());

        return view('missions.show', compact('mission', 'attempts', 'attemptTally', 'successTally'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $mission = Mission::find($id);

        return view('missions.edit', compact('mission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(UpdateMissionRequest $request, $id)
    {
        $mission = Mission::findOrFail($id);
        $mission->fill($request->all());
        $mission->save();

        return redirect()->route('missions.show', $id)
            ->with('status.success', 'Success! Your mission is now updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/missions/_attempt_active.blade.php
@if ($attempt->status === $status) active @endif

resources/views/missions/_attempt_class.blade.php
@if($attempt->status === 'success')
alert alert-success
@elseif($attempt->status === 'almost')
alert alert-warning
@elseif($attempt->status === 'miss')
alert alert-danger
@else {{-- unchecked --}}
alert alert-info
@endif

resources/views/missions/_form.blade.php
@if(count($errors) > 0)
  <div class="alert alert-danger">There were problems with your form. Please fix them.</div>
@endif

<div class="form-group {{ $errors->has('title') ? 'has-error text-danger' : '' }}">
  <label for="title" class="col-sm-2 control-label">Mission Title</label>
  <div class="col-sm-10">
    {!! Form::text('title', $mission->title, ['class' => 'form-control']) !!}
    @include('partials.error-help-block', ['field' => 'title'])
  </div>
</div>

<div class="form-group {{ $errors->has('description') ? 'has-error text-danger' : '' }}">
  <label for="description" class="col-sm-2 control-label">Description</label>
  <div class="col-sm-10">
    {!! Form::textarea('description', $mission->description, ['class' => 'form-control', 'rows' => '5']) !!}
    @include('partials.error-help-block', ['field' => 'description'])
  </div>
</div>

<div class="form-group {{ $errors->has('photo') ? 'has-error text-danger' : '' }}">
  <label for="photo" class="col-sm-2 control-label">Answer Photo</label>
  <div class="col-sm-10">
    {!! Form::file('photo', ['class' => 'form-control', 'rows' => '5']) !!}
    @include('partials.error-help-block', ['field' => 'photo'])
  </div>
</div>

resources/views/missions/create.blade.php
@extends('layouts.master')

@section('content')
  <div class="container">
    <h1>Create New Mission</h1>

    {!! Form::open(['route' => 'missions.store', 'class' => 'form-horizontal', 'files' => true]) !!}

      @include('missions._form')

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Create Mission</button>
        </div>
      </div>
    {!! Form::close() !!}
  </div>
@endsection

resources/views/missions/edit.blade.php
@extends('layouts.master')

@section('content')
  <div class="container">
    <h1>Edit Mission</h1>

    {!! Form::open(['route' => ['missions.update', $mission->id], 'class' => 'form-horizontal', 'files' => true]) !!}
      {!! Form::hidden('_method', 'PUT') !!}

      @include('missions._form')

      <div class="form-group">
        <label class="col-sm-2 control-label">Current Photo</label>
        <div class="col-sm-10">
          <img src="{{ $mission->photo->url('thumb') }}" alt="" class="img-rounded">
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Edit Mission</button>
        </div>
      </div>
    {!! Form::close() !!}
  </div>
@endsection

resources/views/missions/index.blade.php
@extends('layouts.master')

@section('content')

  <div class="container">
    <h1>Missions</h1>
    <ul>
      @foreach($missions as $mission)
        <li>
            <a href="{{ route('missions.show', $mission->id) }}">{{ $mission->title }}</a>
            - {{ $mission->user->name }}
        </li>
      @endforeach
    </ul>
    <p><a href="{{ route('missions.create') }}" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Create Mission</a></p>
  </div>
@endsection

resources/views/missions/show.blade.php
@extends('layouts.master')

@section('content')

  <div class="container">

    @if(count($errors) > 0)
      <div class="alert alert-danger">There were problems with your attempt form. Please scroll down and fix them.</div>
    @endif

    <h1>{{ $mission->title }}</h1>
    <p>{{ $mission->description }}</p>
    <p>
      Made by {{ $mission->user->name }}
      @if(Auth::check() && Auth::user()->id === $mission->user->id)
        (You!)
      @endif
    </p>

    @if(Auth::check() && Auth::user()->id === $mission->user->id)
      <p><img src="{{ $mission->photo->url('hero') }}" alt=""></p>
      <p><a href="{{ route('missions.edit', $mission->id) }}" class="btn btn-default">
      <span class="glyphicon glyphicon-pencil"></span> Edit Mission</a></p>
    @endif

    <h2>Attempts – {{ $successTally }} success from {{ $attemptTally }} attempts</h2>
    <div class="container">
    @foreach($attempts as $attempt)
      @if(Auth::check() && (Auth::user()->id === $mission->user->id || Auth::user()->id === $attempt->user->id))

        <div class="row">
          <div class="col-sm-2">
            <p><img src="{{ $attempt->photo->url('thumb') }}" alt=""
              class="img-rounded @include('missions._attempt_class', ['attempt' => $attempt]) "></p>
          </div>
          <div class="col-sm-10">
            <p>{{ $attempt->user->name }}</p>
            <p>
              <a href="{{ route('missions.attempts.edit', [$mission->id, $attempt->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> Edit Attempt</a>

              @if(Auth::check() && Auth::user()->id === $mission->user->id)
                {!! Form::open(['route' => ['missions.attempts.update', $attempt->mission_id, $attempt->id], 'class' => 'attempts-update form-horizontal', 'files' => true, 'method' => 'PUT', 'data-attempt-id' => $attempt->id]) !!}
                  <div class="btn-group" role="group" aria-label="Change Status">
                    <button type="submit" class="btn btn-success @include('missions._attempt_active', ['attempt' => $attempt, 'status' => 'success'])" name="status" value="success">Success</button>
                    <button type="submit" class="btn btn-warning @include('missions._attempt_active', ['attempt' => $attempt, 'status' => 'almost'])" name="status" value="almost">Almost</button>
                    <button type="submit" class="btn btn-danger @include('missions._attempt_active', ['attempt' => $attempt, 'status' => 'miss'])" name="status" value="miss">Miss</button>
                    <button type="submit" class="btn btn-info @include('missions._attempt_active', ['attempt' => $attempt, 'status' => 'unchecked'])" name="status" value="unchecked">Unchecked</button>
                  </div>
                {!! Form::close() !!}
              @endif
            </p>
          </div>
        </div>
      @endif
    @endforeach
    </div>

    <h3>Add New Attempt</h3>
    @if(Auth::check() && Auth::user()->id !== $mission->user->id)
      {!! Form::open(['route' => ['missions.attempts.store', $mission->id], 'class' => 'form-horizontal', 'files' => true]) !!}

        <div class="form-group {{ $errors->has('photo') ? 'has-error text-danger' : '' }}">
          <label for="photo" class="col-sm-2 control-label">Attempt Photo</label>
          <div class="col-sm-10">
            {!! Form::file('photo', ['class' => 'form-control', 'rows' => '5']) !!}
            @include('partials.error-help-block', ['field' => 'photo'])
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Submit Attempt</button>
          </div>
        </div>
      {!! Form::close() !!}

    @elseif(Auth::check() && Auth::user()->id === $mission->user->id)
      <p>You can't submit an attempt on a mission you set.</p>

    @else
      <p><a href="{{ route('auth.login') }}">Log in</a> to submit an attempt on this mission.</p>
    @endif
  </div>
@endsection